(() => {
  const SHARED_CSS=['style.css','interno.css','site-system.css','mobile-app.css','mobile-fix.css','mobile-app-v3.css','mobile-app-final.css','marketplace-final.css','catalog-footer.css','kora-redesign.css','kora-logo.css','auth-reference.css','flashmarket-premium.css','design-system.css'];
  const loadCss=(href,marker)=>{if(document.querySelector(`link[data-${marker}]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.dataset[marker]='true';document.head.appendChild(link)};
  document.querySelectorAll('link[rel="stylesheet"][href]').forEach(link=>{const clean=link.getAttribute('href').split('?')[0].split('/').pop();if(SHARED_CSS.includes(clean))link.remove()});
  loadCss('css/flashmarket.css?v=21','flashmarketCoreCss');
  loadCss('css/mobile-exclusive.css?v=1','mobileExclusiveCss');
  const isAffiliate=/\/afiliado\.html$/i.test(location.pathname),isHome=/\/index\.html$/i.test(location.pathname)||/\/$/.test(location.pathname);
  if(isHome)loadCss('css/home-commerce.css?v=21','homeCommerceCss');
  if(isAffiliate){loadCss('css/mobile-affiliate.css?v=21','mobileAffiliateCss');loadCss('css/affiliate-live.css?v=21','affiliateLiveCss')}
  const loadScript=(src,marker)=>{if(document.querySelector(`script[data-${marker}]`))return;const s=document.createElement('script');s.src=src;s.defer=true;s.dataset[marker]='true';document.head.appendChild(s)};
  loadScript('js/mobile-app.js','mobileAppJs');loadScript('js/ui-final.js','uiFinalJs');if(isHome)loadScript('js/home-commerce.js','homeCommerceJs');if(isAffiliate)loadScript('js/affiliate-live.js','affiliateLiveJs');
  function normalizeSharedUI(){document.querySelectorAll('.brand-logo,.logo img,.logo-image,.site-logo,.footer-logo,img[alt*="FlashMarket" i],img[alt*="FLASH MARKET" i]').forEach(img=>{if(img.tagName==='IMG')img.src='assets/logo-kora.svg'});const fs=[...document.querySelectorAll('footer')];if(fs.length>1)fs.slice(1).forEach(el=>el.remove())}
  function arrangeHomeSections(){if(!isHome)return;const main=document.querySelector('main#inicio'),offers=document.querySelector('#ofertas'),products=document.querySelector('#produtos,#mais-produtos'),catalog=document.querySelector('#catalogo,#categorias');if(!main||!offers||!products||!catalog)return;main.style.display='flex';main.style.flexDirection='column';main.style.alignItems='stretch';offers.style.order='1';products.style.order='2';catalog.style.order='3';const t=products.querySelector('.section-head h2');if(t)t.textContent='Mais produtos';const ct=catalog.querySelector('.section-head h2');if(ct)ct.textContent='Compre por categoria'}
  function initAffiliateSessionUI(){if(!isAffiliate)return;const authArea=document.getElementById('authArea')||document.querySelector('.auth-box'),dashboard=document.getElementById('affiliatePanel')||document.querySelector('.affiliate-card');if(!authArea||!dashboard)return;const loggedIn=()=>localStorage.getItem('flashmarket_affiliate_session')==='true'&&!!localStorage.getItem('flashmarket_access_token');const sync=()=>{const active=loggedIn();authArea.hidden=active;dashboard.hidden=!active;authArea.style.display=active?'none':'';dashboard.style.display=active?'':'none'};sync();document.addEventListener('submit',e=>{if(e.target?.closest('#authForm,.auth-form')){setTimeout(sync,150);setTimeout(sync,800)}});window.addEventListener('storage',sync)}
  let deferredPrompt=null;
  const installButton=document.createElement('button');installButton.type='button';installButton.className='pwa-install';installButton.textContent='↥ INSTALAR APP';installButton.hidden=true;document.body.appendChild(installButton);
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installButton.hidden=false});
  async function requestInstall(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installButton.hidden=true;return}alert('No iPhone/iPad: toque em Compartilhar e depois Adicionar à Tela de Início. No Android: abra o menu do navegador e toque em Instalar app ou Adicionar à tela inicial.')}
  installButton.addEventListener('click',requestInstall);const footerInstall=document.querySelector('.footer-install');if(footerInstall)footerInstall.addEventListener('click',requestInstall);window.addEventListener('appinstalled',()=>{deferredPrompt=null;installButton.hidden=true});
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.error('PWA FlashMarket:',e)));
  const style=document.createElement('style');style.textContent='.pwa-install{position:fixed;right:14px;bottom:16px;z-index:1100;border:0;border-radius:999px;padding:13px 18px;background:#ff4d2d;color:#fff;font:900 11px Inter,Arial,sans-serif;box-shadow:0 10px 28px #0004}.pwa-install[hidden]{display:none}@media(max-width:700px){.pwa-install{right:12px;bottom:calc(82px + env(safe-area-inset-bottom));padding:12px 15px}}@media(display-mode:standalone){.pwa-install{display:none}}';document.head.appendChild(style);
  const init=()=>{normalizeSharedUI();arrangeHomeSections();initAffiliateSessionUI()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();