(()=>{const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const faqData=[
['Como acompanho meu pedido?','Acesse Rastrear Pedido e informe o número do pedido ou o código de rastreio recebido após a compra.','rastrear-pedido.html'],
['Meu pagamento foi aprovado. E agora?','Após a confirmação, o pedido é registrado e você pode acompanhar as etapas pela sua conta ou pela página de rastreamento.'],
['Como faço uma troca ou devolução?','Entre na sua conta, abra os detalhes do pedido e use a opção de atendimento para registrar a solicitação.'],
['Como altero meus dados da conta?','Acesse Minha conta e entre em Meus dados para atualizar as informações disponíveis no seu perfil.','minha-conta.html'],
['Esqueci minha senha. O que faço?','Na tela de login, use a opção de recuperação de senha para iniciar o processo.','login.html'],
['Onde encontro meus cupons?','Abra Minha conta para consultar os benefícios disponíveis.','minha-conta.html'],
['O que faço se meu pedido atrasar?','Consulte primeiro o rastreamento. Se o status não mudar ou houver divergência, abra uma solicitação no suporte com o número do pedido.']
];
function toast(t){if(typeof fmToast==='function'){fmToast(t);return}let e=$('.fm-toast');if(!e){e=document.createElement('div');e.className='fm-toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function renderFaq(filter=''){const box=$('#supportFaq');if(!box)return;const q=filter.trim().toLowerCase();box.innerHTML='';let visible=0;faqData.forEach(([title,text,link])=>{if(q&&!(title+' '+text).toLowerCase().includes(q))return;visible++;const d=document.createElement('details');d.className='faq-item';d.innerHTML='<summary>'+title+'</summary><div class="faq-answer">'+text+(link?' <a href="'+link+'">Acessar agora →</a>':'')+'</div>';box.appendChild(d)});if(!visible)box.innerHTML='<div class="fm-alert">Não encontramos uma resposta para sua busca. Tente outro termo ou envie uma solicitação para nossa equipe.</div>'}
function focusFaq(term){const input=$('#faqSearch');if(input)input.value=term;renderFaq(term);$('#faqSection')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#supportFaq details')?.setAttribute('open',''),350)}
window.focusFaq=focusFaq;
$('#supportSearch')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#supportQuery').value.trim();if(!q){$('#supportQuery').focus();return}renderFaq(q);$('#faqSection')?.scrollIntoView({behavior:'smooth',block:'start'})});
$('#faqSearch')?.addEventListener('input',e=>renderFaq(e.target.value));
$$('[data-topic]').forEach(b=>b.addEventListener('click',()=>focusFaq(b.dataset.topic)));
$('#trackForm')?.addEventListener('submit',async e=>{e.preventDefault();const code=$('#trackCode').value.trim();const result=$('#trackResult');if(!code){result.innerHTML='<strong>Digite seu pedido ou código de rastreio.</strong>';result.classList.add('show');return}result.innerHTML='<strong>Consultando pedido…</strong><span>Buscando os dados reais de pagamento e rastreamento.</span>';result.classList.add('show');try{const base=window.FLASHMARKET_API_BASE||(location.hostname.endsWith('github.io')?'https://koramarketplace.vercel.app':'');const r=await fetch(base+'/api/payments/status?order='+encodeURIComponent(code),{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Pedido não encontrado.');const o=d.order||{};const last=Array.isArray(o.tracking)&&o.tracking.length?o.tracking[o.tracking.length-1]:null;result.innerHTML='<strong>✓ Pedido encontrado · '+(o.id||code)+'</strong><span>'+(last?.title||o.paymentStatus||'Pedido registrado')+' · '+(o.trackingCode?'Código '+o.trackingCode:'Aguardando código de rastreio')+'</span><br><a href="rastrear-pedido.html?order='+encodeURIComponent(o.id||code)+'" style="display:inline-block;margin-top:7px;color:#ee4d2d;font-weight:900">Ver rastreamento completo →</a>'}catch(x){result.innerHTML='<strong>Pedido não encontrado.</strong><span>'+(x.message||'Confira o número ou código e tente novamente.')+'</span>'}});
$('#ticketForm')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());const token=localStorage.getItem('flashmarket_access_token');if(!token){const ret=location.pathname+location.search;location.href='login.html?return='+encodeURIComponent(ret);return}const button=e.currentTarget.querySelector('button[type=submit]'),ok=$('#ticketSuccess');button.disabled=true;button.textContent='ENVIANDO…';try{const base=window.FLASHMARKET_API_BASE||(location.hostname.endsWith('github.io')?'https://koramarketplace.vercel.app':'');const r=await fetch(base+'/api/auth/me',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action:data.type==='cancelamento'?'cancel_request':data.type==='devolucao'?'return_request':'support_create',publicId:String(data.order||'').trim(),type:data.type,message:String(data.message||'').trim()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não foi possível abrir o atendimento.');e.currentTarget.reset();if(ok){ok.textContent='Chamado '+(d.ticketId||'')+' registrado com sucesso. Você pode acompanhar as respostas nos detalhes do pedido.';ok.style.display='block'}toast('Atendimento registrado com sucesso.')}catch(x){if(ok){ok.textContent=x.message||'Não foi possível abrir o atendimento.';ok.style.display='block'}else toast(x.message||'Não foi possível abrir o atendimento.')}finally{button.disabled=false;button.textContent='ENVIAR SOLICITAÇÃO →'}});
renderFaq();
})();