(()=>{const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const faqData=[
['Como acompanho meu pedido?','Acesse Rastrear Pedido e informe o número do pedido ou o código de rastreio recebido após a compra.','rastrear-pedido.html'],
['Meu pagamento foi aprovado. E agora?','Após a confirmação, o pedido é registrado e você pode acompanhar as etapas pela área Minhas compras ou pela página de rastreamento.'],
['Como faço uma troca ou devolução?','Entre em contato com o suporte informando o número do pedido, o produto e o motivo da solicitação. A equipe orientará os próximos passos.'],
['Como altero meus dados da conta?','Acesse Minha conta e entre em Meus dados para atualizar as informações disponíveis no seu perfil.','minha-conta.html'],
['Esqueci minha senha. O que faço?','Na tela de login, use a opção de recuperação de senha para iniciar o processo.','login.html'],
['Onde encontro meus cupons?','Abra Minha conta e acesse Meus cupons para consultar códigos, descontos e condições disponíveis.','minha-conta.html'],
['O que faço se meu pedido atrasar?','Consulte primeiro o rastreamento. Se o status não mudar ou houver divergência, abra uma solicitação no suporte com o número do pedido.']
];
function toast(t){if(typeof fmToast==='function'){fmToast(t);return}let e=$('.fm-toast');if(!e){e=document.createElement('div');e.className='fm-toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function renderFaq(filter=''){const box=$('#supportFaq');if(!box)return;const q=filter.trim().toLowerCase();box.innerHTML='';let visible=0;faqData.forEach(([title,text,link])=>{if(q&&!(`${title} ${text}`).toLowerCase().includes(q))return;visible++;const d=document.createElement('details');d.className='faq-item';d.innerHTML=`<summary>${title}</summary><div class="faq-answer">${text}${link?` <a href="${link}">Acessar agora →</a>`:''}</div>`;box.appendChild(d)});if(!visible)box.innerHTML='<div class="fm-alert">Não encontramos uma resposta para sua busca. Tente outro termo ou envie uma solicitação para nossa equipe.</div>'}
function focusFaq(term){const input=$('#faqSearch');if(input)input.value=term;renderFaq(term);$('#faqSection')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#supportFaq details')?.setAttribute('open',''),350)}
window.focusFaq=focusFaq;
$('#supportSearch')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#supportQuery').value.trim();if(!q){$('#supportQuery').focus();return}renderFaq(q);$('#faqSection')?.scrollIntoView({behavior:'smooth',block:'start'})});
$('#faqSearch')?.addEventListener('input',e=>renderFaq(e.target.value));
$$('[data-topic]').forEach(b=>b.addEventListener('click',()=>focusFaq(b.dataset.topic)));
$('#trackForm')?.addEventListener('submit',e=>{e.preventDefault();const code=$('#trackCode').value.trim();const result=$('#trackResult');if(!code){result.innerHTML='<strong>Digite seu pedido ou código de rastreio.</strong><span>Ex.: FM-20260930-123456 ou FM123456789BR</span>';result.classList.add('show');return}let orders=[];try{orders=JSON.parse(localStorage.getItem('flashmarket_orders')||'[]')}catch{}const normalize=x=>String(x||'').toLowerCase().replace(/\s+/g,'');const hit=orders.find(o=>normalize(o.orderNumber)===normalize(code)||normalize(o.trackingCode)===normalize(code)||normalize(o.codigoRastreio)===normalize(code)||normalize(o.id)===normalize(code));if(hit){result.innerHTML=`<strong>✓ Pedido encontrado · ${hit.orderNumber||hit.id||'FlashMarket'}</strong><span>${hit.status||'Pedido confirmado'} · Código ${hit.trackingCode||hit.codigoRastreio||'gerado no pedido'}</span><br><a href="rastrear-pedido.html" style="display:inline-block;margin-top:7px;color:#ee4d2d;font-weight:900">Ver rastreamento completo →</a>`}else{result.innerHTML='<strong>Pedido não encontrado neste dispositivo.</strong><span>Confira o número ou código e tente novamente. No modo demonstração, os pedidos ficam salvos no navegador usado na compra.</span>'}result.classList.add('show')});
$('#ticketForm')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());const ticket={id:`SUP-${Date.now().toString().slice(-8)}`,...data,createdAt:new Date().toISOString(),status:'aberto'};let list=[];try{list=JSON.parse(localStorage.getItem('flashmarket_support_tickets')||'[]')}catch{}list.unshift(ticket);localStorage.setItem('flashmarket_support_tickets',JSON.stringify(list));e.currentTarget.reset();toast(`Solicitação ${ticket.id} registrada`);const ok=$('#ticketSuccess');if(ok){ok.textContent=`Solicitação ${ticket.id} registrada com sucesso. No modo demonstração, ela fica salva neste navegador.`;ok.style.display='block'}});
renderFaq();
})();
